width: 1280
height: 920
compass:
    cx: 200
    cy: 200
    d: 300
artificial_horizon:
    cx: 1200
    cy: 200
    d: 300
altitutde:
    cx: 1100
    cy: 800
linear_velocity:
    cx: 1100
    cy: 800