topics: 
    odm_sub: "/firefly/ground_truth/odometry"
    cam_sub: "/firefly/vi_sensor/right/image_raw"
    cam_compressed_sub: "/firefly/vi_sensor/right/image_raw/compressed"
    hpe_zone_sub: "/stickman_cont_area"
    ui_pub: "/uav/gui"
